import type { Metadata } from "next";
import Header from '@/components/header';
import "./globals.css";
import FontAwesomeConfig from "@/app/fontawesome";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <FontAwesomeConfig />
      </head>
      <body className={`antialiased`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
