import type { Metadata } from "next";
import Header from "@/components/header";
import { NavbarHome } from "@/components/navbar";
import { DesktopNavLinksHome } from "@/components/DesktopNavLinks";
import MobileDrawer from "@/components/MobileDrawer";
import { HomeDrawerLink } from "@/components/drawerLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavbarHome
        desktopChildren={<DesktopNavLinksHome />}
        mobileChildren={<HomeDrawerLink />}
      />
      <main className="px-6 bg-gray-900">{children}</main>
    </>
  );
}
